# a docker compose file for mysql and adminer with a volume for the database and setup for environment variables

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nitesh
      MYSQL_DATABASE: nitesh_ramola
      MYSQL_USER: nitesh
      MYSQL_PASSWORD: ramola
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  # adminer:
  #   image: adminer:latest
  #   container_name: adminer_container
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #   networks:
  #     - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
